### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by PenetratingShot** [CitronJS/CitronJS#12]
Some more bug fixes. This is just for triangle but comment down below for others

**Comment by talonbragg** [comment]
What is wrong with the triangle, can you please provide a brief description? Also, why did you assign Sid and Carson?

**Comment by RocosCodes** [comment]
WHY NOT?

**Comment by talonbragg** [comment]
Could you also please answer my first question, that would be more helpful.

**Comment by PenetratingShot** [comment]
There were conflicting variables in the src and and template

**Comment by PenetratingShot** [comment]
Boom
