### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by PenetratingShot** [CitronJS/CitronJS#15]
@talonbragg, apparently we don't have bower for CitronJS. It doesn't popup on [bower.io](bower.io/search). I was wondering if you could register CitronJS for Bower

**Comment by talonbragg** [comment]
Ok I was working on issues with versioning, um also, I had to work on some issues with the copyright cause somebody took our code and tried to distribute it. They wish to remain anonymous though. The copyright works, the code is ours, he can't distribute it. But I will do him his wish and keep him anonymous.

**Comment by PenetratingShot** [comment]
Alright

**Comment by PenetratingShot** [comment]
Oh and the npm version is now 0.1.1 with the addition of semicircle

**Comment by talonbragg** [comment]
I'm going to do this when I get home.

**Comment by talonbragg** [comment]
Done
