### ISSUE TITLE
Templates and Cleanup

### ISSUE THREAD

**Issue by PenetratingShot** [CitronJS/CitronJS#16]
@CitronJS/admin and @CitronJS/maintainers, work on updating templates for the following: 

- arc
- quadratic curve

And format older files (the very first ones) and keep comments virtually the same

**Comment by PenetratingShot** [comment]
Once this is done we'll try to bump up to v0.1.0 😃

**Comment by talonbragg** [comment]
No, we can bump it up to v0.0.5, We still need 6 more updates because we are currently at v0.0.4.

**Comment by PenetratingShot** [comment]
No we don't, Apple and Microsoft don't always use semantics

**Comment by PenetratingShot** [comment]
I'll try to get past this

**Comment by PenetratingShot** [comment]
K, bumped it up to version 0.1.0 😄
