### ISSUE TITLE
Wrapper

### ISSUE THREAD

**Issue by PenetratingShot** [CitronJS/CitronJS#17]
@talonbragg, why do we have `wrapper.js` file in the `root/src/` of the only thing inside is a comment?

Please explain...

**Comment by PenetratingShot** [comment]
Also can you update the gzipped file? That would be helpful as it's deprecated

**Comment by talonbragg** [comment]
Please explain, really? You need an explanation for this? Wow. Ok, here goes, you need something to put the code in otherwise you can't build it! Simple as that!

**Comment by PenetratingShot** [comment]
...
