### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by PenetratingShot** [CitronJS/CitronJS#5]
Bump versioning from 0.0.1 to 0.2.0 for new update. Update on NPM and unpkg..

**Comment by talonbragg** [comment]
I will do this when I get home.

**Comment by PenetratingShot** [comment]
Alright I'll go on my PI, clone, and publish

**Comment by talonbragg** [comment]
The versioning on npm has not been updated. I'm going to go do that right now.

**Comment by PenetratingShot** [comment]
U got this versioning wrong. It's 0.0.2 not 0.0.2 talon

**Comment by PenetratingShot** [comment]
Whatever
